agm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from .views import *

from .views import *


urlpatterns = [
    # venues

    # path("process-
    # 
    # venues
    path("addcomiser/", comiser_add, name="addcomiser"),
    path("teccred/", generate_accreditation_pdf, name="teaccred"),
    path("comisers/", comisers, name="comisers"),
    path("comiser/<int:id>", comiser_details, name="comiser"),
    path("delete_comiser/<int:id>", comiser_delete, name="delete_comiser"),
    path("update_comiser/<int:id>", comiser_update, name="update_comiser"),
    # path("process-p
    # payment/", process_payment, name="process_payment"),  # Add this line
    # Add more URLs as ne
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *



urlpatterns = [
    path("dashboard/", dashboard, name="dashboard"),
    path("seasons/", seasons_view, name="seasons"),
    path("venues/", venues_view, name="venues"),
    path("courses/", courses_view, name="courses"),
  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

from accounts.models import User




class District(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name



class Season(models.Model):
    name = models.CharField(max_length=50)
    start_date = models.DateField()
    year = models.IntegerField()
    status = models.CharField( choices=[("Active", "Active"), ("Inactive", "Inactive")], max_length=10, default="Active" ,null=True, blank=True)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self):
        return self.name


class Venue(models.Model):
    name = models.CharField(max_length=50)
    season = models.ForeignKey(Season, on_delete=models.CASCADE)
    courses = models.ManyToManyField('Course', blank=True)
    status = models.CharField( choices=[("Active", "Active"), ("Inactive", "Inactive")], max_length=10, default="Active" ,null=True, blank=True)
    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=50)
    level = models.ManyToManyField('Level', null=True, blank=True)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.name}"
    

    
class Level(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

dashboard/forms.py
from django import forms
from .models import *


class SeasonForm(forms.ModelForm):
    class Meta:
        model = Season
        fields = [
            "name",
            "start_date",
            "year",
        ]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "start_date": forms.DateInput(attrs={"type": "date", "class": "form-control"}),
            "year": forms.NumberInput(attrs={"class": "form-control"}),
        }

class VenueForm(forms.ModelForm):
    class Meta:
        model = Venue
        fields = [
            "name",
            "season",
            "courses",
        ]
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            # Filter the championship queryset to only include active championships
            self.fields['season'].queryset = Season.objects.filter(status='Active')
            
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "season": forms.Select(attrs={"class": "form-control"}),
            "courses": forms.SelectMultiple(attrs={"class": "form-control js-example-basic-multiple-name"}),
        }
class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = [
            "name",
            "level",
        ]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "level": forms.Select(attrs={"class": "form-control"}),
        }
class LevelForm(forms.ModelForm):
    class Meta:
        model = Level
        fields = [
            "name",
        ]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
        }   

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *

# Create your views here.
@login_required(login_url='login')
def dashboard(request):
    context = {}
    return render(request, "dashboard/overview.html", context)



@login_required(login_url='login')
def seasons_view(request):
    user = request.user
    seasons = Season.objects.filter(status="Active").order_by('-start_date')
    new_season = None
    season_to_edit = None

    # Check if we're editing
    season_id = request.GET.get("edit") or request.POST.get("season_id")
    if season_id:
        season_to_edit = get_object_or_404(Season, id=season_id)

    if request.method == "POST":
        if season_to_edit:
            cform = SeasonForm(request.POST, request.FILES, instance=season_to_edit)
        else:
            cform = SeasonForm(request.POST, request.FILES)

        if cform.is_valid():
            new_season = cform.save(commit=False)
            if not season_to_edit:  # Only set these when creating
                new_season.added_by = user
            new_season.save()
            return redirect("seasons")
    else:
        if season_to_edit:
            cform = SeasonForm(instance=season_to_edit)
        else:
            cform = SeasonForm()

    context = {
        "seasons": seasons,
        "cform": cform,
        "season_to_edit": season_to_edit,
    }

    return render(request, "elements/seasons.html", context)



@login_required(login_url='login')
def venues_view(request):
    user = request.user
    venues = Venue.objects.filter(status="Active")
    new_venue = None
    venue_to_edit = None

    # Check if we're editing
    venue_id = request.GET.get("edit") or request.POST.get("venue_id")
    if venue_id:
        venue_to_edit = get_object_or_404(Venue, id=venue_id)

    if request.method == "POST":
        if venue_to_edit:
            cform = VenueForm(request.POST, request.FILES, instance=venue_to_edit)
        else:
            cform = VenueForm(request.POST, request.FILES)

        if cform.is_valid():
            selected_courses = cform.cleaned_data["courses"]
            new_venue = cform.save(commit=False)
            if not venue_to_edit:  # Only set these when creating
                new_venue.added_by = user
                
            new_venue.save()
            new_venue.courses.set(selected_courses)
            return redirect("venues")
    else:
        if venue_to_edit:
            cform = VenueForm(instance=venue_to_edit)
        else:
            cform = VenueForm()

    context = {
        "venues": venues,
        "cform": cform,
        "venue_to_edit": venue_to_edit,
    }

    return render(request, "elements/venues.html", context)

@login_required(login_url='login')
def courses_view(request):
    user = request.user
    courses = Course.objects.all()
    new_course = None
    course_to_edit = None

    # Check if we're editing
    course_id = request.GET.get("edit") or request.POST.get("course_id")
    if course_id:
        course_to_edit = get_object_or_404(Course, id=course_id)

    if request.method == "POST":
        if course_to_edit:
            cform = CourseForm(request.POST, request.FILES, instance=course_to_edit)
        else:
            cform = CourseForm(request.POST, request.FILES)

        if cform.is_valid():
            
            new_course = cform.save(commit=False)
            if not course_to_edit:  # Only set these when creating
                new_course.added_by = user
                
            new_course.save()
            return redirect("courses")
    else:
        if course_to_edit:
            cform = CourseForm(instance=course_to_edit)
        else:
            cform = CourseForm()

    context = {
        "courses": courses,
        "cform": cform,
        "course_to_edit": course_to_edit,
    }

    return render(request, "elements/courses.html", context)

dashboard/templates/assets/css.html
{% load static %}
<link
  href="{% static 'css/app.min.css'%}"
  rel="stylesheet"
  type="text/css"
  id="app-style"
/>

<!-- Icons -->
<link href="{% static 'css/icons.min.css'%}" rel="stylesheet" type="text/css" />
<link
  href="{% static 'css/material-icons.min.css'%}"
  rel="stylesheet"
  type="text/css"
/>

<script src="{% static 'js/head.js'%}"></script>
<!--<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css"
  integrity="sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>//-->
{% comment %}
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/material-icons@1.13.14/iconfont/material-icons.min.css"
/>
{% endcomment %}

<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/@mdi/font@7.4.47/css/materialdesignicons.min.css"
/>
<link
  rel="stylesheet"
  href="https://cdn.datatables.net/2.3.4/css/dataTables.dataTables.css"
/>

<link
  href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"
  rel="stylesheet"
/>

dashboard/templates/assets/js.html
{% load static %}

<!-- END wrapper -->
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
  integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
></script>
<!-- Vendor -->

<script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
<script src="{% static 'js/iconify-icon.min.js'%}"></script>
<script src="{% static 'js/simplebar.min.js'%}"></script>
<script src="{% static 'js/waves.min.js'%}"></script>
<script src="{% static 'js/jquery.waypoints.min.js'%}"></script>
<script src="{% static 'js/jquery.counterup.min.js'%}"></script>
<script src="{% static 'js/feather.min.js'%}"></script>

<!-- Apexcharts JS -->
<script src="{% static 'js/apexcharts.min.js'%}"></script>

<!-- Vector map-->
<script src="{% static 'js/jsvectormap.min.js'%}"></script>
<script src="{% static 'js/world-merc.js'%}"></script>

<!-- Widgets Init Js -->
<script src="{% static 'js/crm-dashboard.init.js'%}"></script>

<!-- App js-->
<script src="{% static 'js/app.js'%}"></script>

<script src="https://cdn.datatables.net/2.3.4/js/dataTables.js"></script>
<script>
  $(document).ready(function () {
    $("#schools").DataTable();
  });
</script>

<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
  integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
  crossorigin="anonymous"
></script>

<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

<script>
  $(document).ready(function () {
    $(".js-example-basic-multiple-name").select2({
      placeholder: "Select courses names",
      allowClear: true,
    });
  });
  $("#id_courses").select2({
    dropdownParent: $("#venuesModalLabel"),
  });
  
// In your Javascript (external .js resource or <script> tag)
$(document).ready(function() {
    $('.js-example-basic-single').select2();
});
</script>